"""Seed data for temples and packages."""
from typing import List, Dict, Any


def slugify(name: str) -> str:
    return name.lower().replace(" ", "-").replace("'", "").replace(",", "")


TEMPLES_RAW: List[Dict[str, Any]] = [
    # NORTH INDIA
    {"name": "Vaishno Devi", "region": "north_india", "state_or_country": "Jammu & Kashmir, India",
     "deity": "Mata Vaishno Devi", "elevation_m": 1584, "best_season": "March - October",
     "darshan_timings": "5:00 AM - 12:00 PM, 4:00 PM - 9:00 PM",
     "significance": "One of the most revered Shakti Peethas, set in the Trikuta mountains.",
     "history": "Pilgrims have been visiting this cave shrine for over a thousand years.",
     "nearest_airport": "Jammu (IXJ)", "nearest_railway": "Katra (SVDK)",
     "vip_darshan": True, "requires_trek": True, "trek_distance_km": 13.0, "trek_difficulty": "moderate",
     "lat": 33.0307, "lng": 74.9494, "festival_dates": ["Navratri (Mar/Apr & Sep/Oct)"]},
    {"name": "Kedarnath", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Lord Shiva (Jyotirlinga)", "elevation_m": 3583, "best_season": "May - October",
     "darshan_timings": "4:00 AM - 9:00 PM",
     "significance": "One of the twelve Jyotirlingas and part of the Char Dham Yatra.",
     "history": "Built by the Pandavas and revived by Adi Shankaracharya in the 8th century.",
     "nearest_airport": "Dehradun (DED)", "nearest_railway": "Rishikesh (RKSH)",
     "vip_darshan": True, "requires_trek": True, "trek_distance_km": 16.0, "trek_difficulty": "hard",
     "lat": 30.7346, "lng": 79.0669, "festival_dates": ["Maha Shivaratri", "Kedar Mela"]},
    {"name": "Badrinath", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Lord Vishnu", "elevation_m": 3133, "best_season": "May - October",
     "darshan_timings": "4:30 AM - 1:00 PM, 4:00 PM - 9:00 PM",
     "significance": "One of the Char Dhams and 108 Divya Desams of Vishnu.",
     "history": "Established by Adi Shankaracharya; the temple sits beside the Alaknanda river.",
     "nearest_airport": "Dehradun (DED)", "nearest_railway": "Rishikesh (RKSH)",
     "lat": 30.7433, "lng": 79.4938, "festival_dates": ["Mata Murti ka Mela", "Badri Kedar Utsav"]},
    {"name": "Gangotri", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Goddess Ganga", "elevation_m": 3100, "best_season": "May - October",
     "darshan_timings": "6:00 AM - 7:30 PM",
     "significance": "Source of the holy Ganga and part of Char Dham.",
     "nearest_airport": "Dehradun (DED)", "nearest_railway": "Rishikesh (RKSH)",
     "lat": 30.9947, "lng": 78.9398, "festival_dates": ["Ganga Dussehra"]},
    {"name": "Yamunotri", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Goddess Yamuna", "elevation_m": 3293, "best_season": "May - October",
     "darshan_timings": "6:00 AM - 8:00 PM",
     "significance": "Source of river Yamuna and part of Char Dham.",
     "requires_trek": True, "trek_distance_km": 6.0, "trek_difficulty": "moderate",
     "lat": 31.0151, "lng": 78.4517, "festival_dates": ["Yamuna Jayanti"]},
    {"name": "Amarnath", "region": "north_india", "state_or_country": "Jammu & Kashmir, India",
     "deity": "Lord Shiva (Ice Lingam)", "elevation_m": 3888, "best_season": "July - August",
     "darshan_timings": "Open only during Shravan Mela",
     "significance": "Sacred ice lingam that forms naturally each summer.",
     "requires_trek": True, "trek_distance_km": 42.0, "trek_difficulty": "hard",
     "lat": 34.2148, "lng": 75.5009, "festival_dates": ["Shravan Mela (Jul-Aug)"]},
    {"name": "Kashi Vishwanath", "region": "north_india", "state_or_country": "Uttar Pradesh, India",
     "deity": "Lord Shiva (Jyotirlinga)", "elevation_m": 80, "best_season": "October - March",
     "darshan_timings": "2:30 AM - 11:00 PM",
     "significance": "One of the twelve Jyotirlingas in the spiritual capital Varanasi.",
     "nearest_airport": "Varanasi (VNS)", "nearest_railway": "Varanasi Junction",
     "vip_darshan": True, "lat": 25.3109, "lng": 83.0107,
     "festival_dates": ["Maha Shivaratri", "Dev Deepawali"]},
    {"name": "Haridwar", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Ganga Aarti", "elevation_m": 314, "best_season": "October - March",
     "darshan_timings": "Ganga Aarti at sunset",
     "significance": "Gateway to the Char Dham and host of the Kumbh Mela.",
     "nearest_airport": "Dehradun (DED)", "nearest_railway": "Haridwar (HW)",
     "lat": 29.9457, "lng": 78.1642, "festival_dates": ["Kumbh Mela", "Kanwar Yatra"]},
    {"name": "Rishikesh", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Yoga capital & Shiva", "elevation_m": 372, "best_season": "September - April",
     "darshan_timings": "Triveni Ghat Aarti 6:00 PM",
     "significance": "Yoga capital of the world; gateway to Himalayan pilgrimages.",
     "nearest_airport": "Dehradun (DED)", "nearest_railway": "Haridwar (HW)",
     "lat": 30.0869, "lng": 78.2676, "festival_dates": ["International Yoga Festival"]},
    {"name": "Hemkund Sahib", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Guru Gobind Singh Ji", "elevation_m": 4632, "best_season": "June - September",
     "darshan_timings": "Open seasonally",
     "significance": "Highest gurudwara in the world set beside a glacial lake.",
     "requires_trek": True, "trek_distance_km": 19.0, "trek_difficulty": "hard",
     "lat": 30.7058, "lng": 79.6098, "festival_dates": ["Guru Gobind Singh Jayanti"]},
    {"name": "Tungnath", "region": "north_india", "state_or_country": "Uttarakhand, India",
     "deity": "Lord Shiva (Panch Kedar)", "elevation_m": 3680, "best_season": "April - November",
     "significance": "Highest Shiva temple in the world; part of Panch Kedar.",
     "requires_trek": True, "trek_distance_km": 4.0, "trek_difficulty": "moderate",
     "lat": 30.4894, "lng": 79.2153, "festival_dates": ["Maha Shivaratri"]},

    # EAST INDIA
    {"name": "Kolkata Kali Temple", "region": "east_india", "state_or_country": "West Bengal, India",
     "deity": "Maa Kali", "elevation_m": 12, "best_season": "October - February",
     "darshan_timings": "5:00 AM - 2:00 PM, 5:00 PM - 10:30 PM",
     "significance": "Kalighat Shakti Peetha in the heart of Kolkata.",
     "nearest_airport": "Kolkata (CCU)", "nearest_railway": "Kolkata (HWH)",
     "lat": 22.5202, "lng": 88.3426, "festival_dates": ["Kali Puja", "Durga Puja"]},
    {"name": "Jagannath Puri", "region": "east_india", "state_or_country": "Odisha, India",
     "deity": "Lord Jagannath", "elevation_m": 5, "best_season": "October - February",
     "darshan_timings": "5:00 AM - 12:00 AM",
     "significance": "Char Dham of India; site of the famous Rath Yatra.",
     "nearest_airport": "Bhubaneswar (BBI)", "nearest_railway": "Puri (PURI)",
     "vip_darshan": True, "lat": 19.8048, "lng": 85.8174,
     "festival_dates": ["Rath Yatra (June/July)", "Snana Yatra"]},
    {"name": "Kamakhya Temple", "region": "east_india", "state_or_country": "Assam, India",
     "deity": "Maa Kamakhya", "elevation_m": 150, "best_season": "October - April",
     "darshan_timings": "5:30 AM - 1:00 PM, 2:30 PM - 5:30 PM",
     "significance": "One of the 51 Shakti Peethas atop Nilachal Hill.",
     "nearest_airport": "Guwahati (GAU)", "nearest_railway": "Guwahati (GHY)",
     "lat": 26.1664, "lng": 91.7055, "festival_dates": ["Ambubachi Mela"]},
    {"name": "Baidyanath Dham", "region": "east_india", "state_or_country": "Jharkhand, India",
     "deity": "Lord Shiva (Jyotirlinga)", "elevation_m": 254, "best_season": "October - March",
     "significance": "One of the twelve Jyotirlingas; site of the Shravani Mela.",
     "nearest_airport": "Deoghar (DGH)", "nearest_railway": "Jasidih (JSME)",
     "lat": 24.4881, "lng": 86.7008, "festival_dates": ["Shravani Mela"]},
    {"name": "Dakshineswar Temple", "region": "east_india", "state_or_country": "West Bengal, India",
     "deity": "Maa Bhavatarini", "best_season": "October - February",
     "significance": "Sacred site associated with Sri Ramakrishna Paramahamsa.",
     "lat": 22.6552, "lng": 88.3576, "festival_dates": ["Kali Puja"]},

    # WEST INDIA
    {"name": "Somnath", "region": "west_india", "state_or_country": "Gujarat, India",
     "deity": "Lord Shiva (Jyotirlinga)", "best_season": "October - March",
     "darshan_timings": "6:00 AM - 9:30 PM",
     "significance": "First among the twelve Jyotirlingas on the Arabian Sea coast.",
     "nearest_airport": "Diu (DIU)", "nearest_railway": "Veraval (VRL)",
     "lat": 20.8880, "lng": 70.4012, "festival_dates": ["Maha Shivaratri", "Kartik Purnima"]},
    {"name": "Dwarkadhish", "region": "west_india", "state_or_country": "Gujarat, India",
     "deity": "Lord Krishna", "best_season": "October - February",
     "darshan_timings": "6:30 AM - 1:00 PM, 5:00 PM - 9:30 PM",
     "significance": "One of the Char Dhams marking Lord Krishna's kingdom.",
     "lat": 22.2381, "lng": 68.9685, "festival_dates": ["Janmashtami"]},
    {"name": "Siddhivinayak", "region": "west_india", "state_or_country": "Maharashtra, India",
     "deity": "Lord Ganesha", "best_season": "Year round",
     "darshan_timings": "5:30 AM - 9:50 PM",
     "significance": "Iconic Ganesha temple in Mumbai with rich daily darshans.",
     "lat": 19.0176, "lng": 72.8302, "festival_dates": ["Ganesh Chaturthi"]},
    {"name": "Shirdi Sai Baba", "region": "west_india", "state_or_country": "Maharashtra, India",
     "deity": "Sai Baba", "best_season": "October - March",
     "darshan_timings": "4:00 AM - 11:15 PM",
     "significance": "Samadhi temple of Sri Sai Baba of Shirdi.",
     "vip_darshan": True, "lat": 19.7674, "lng": 74.4769,
     "festival_dates": ["Guru Purnima", "Vijayadashami"]},
    {"name": "Golden Temple Amritsar", "region": "west_india", "state_or_country": "Punjab, India",
     "deity": "Sri Harmandir Sahib", "best_season": "October - March",
     "darshan_timings": "Open 24 hours",
     "significance": "Holiest gurudwara of Sikhism, set in the Amrit Sarovar.",
     "lat": 31.6200, "lng": 74.8765, "festival_dates": ["Guru Nanak Jayanti", "Vaisakhi"]},
    {"name": "Trimbakeshwar", "region": "west_india", "state_or_country": "Maharashtra, India",
     "deity": "Lord Shiva (Jyotirlinga)", "best_season": "October - March",
     "significance": "Jyotirlinga near the source of the Godavari river.",
     "lat": 19.9332, "lng": 73.5300, "festival_dates": ["Maha Shivaratri", "Kumbh Mela"]},

    # CENTRAL INDIA
    {"name": "Ujjain Mahakaleshwar", "region": "central_india", "state_or_country": "Madhya Pradesh, India",
     "deity": "Lord Shiva (Jyotirlinga)", "best_season": "October - March",
     "darshan_timings": "3:00 AM - 11:00 PM (Bhasma Aarti at 4 AM)",
     "significance": "Self-manifested Jyotirlinga famed for the Bhasma Aarti.",
     "vip_darshan": True, "lat": 23.1828, "lng": 75.7682,
     "festival_dates": ["Maha Shivaratri", "Simhastha Kumbh"]},
    {"name": "Omkareshwar", "region": "central_india", "state_or_country": "Madhya Pradesh, India",
     "deity": "Lord Shiva (Jyotirlinga)", "best_season": "October - March",
     "significance": "Jyotirlinga on an Om-shaped island in the Narmada river.",
     "lat": 22.2410, "lng": 76.1492, "festival_dates": ["Maha Shivaratri", "Kartik Purnima"]},
    {"name": "Sanchi Stupa", "region": "central_india", "state_or_country": "Madhya Pradesh, India",
     "deity": "Buddhist heritage", "best_season": "October - March",
     "significance": "UNESCO Buddhist stupa commissioned by Emperor Ashoka.",
     "lat": 23.4795, "lng": 77.7395, "festival_dates": ["Buddha Purnima"]},
    {"name": "Chitrakoot", "region": "central_india", "state_or_country": "Madhya Pradesh, India",
     "deity": "Lord Rama", "best_season": "October - March",
     "significance": "Where Lord Rama spent 11 years of his exile.",
     "lat": 25.2000, "lng": 80.8500, "festival_dates": ["Ram Navami", "Diwali"]},

    # SOUTH INDIA
    {"name": "Tirupati Balaji", "region": "south_india", "state_or_country": "Andhra Pradesh, India",
     "deity": "Lord Venkateswara", "elevation_m": 853, "best_season": "October - March",
     "darshan_timings": "Open 24 hours (slots by booking)",
     "significance": "Most-visited Hindu temple in the world.",
     "vip_darshan": True, "nearest_airport": "Tirupati (TIR)", "nearest_railway": "Tirupati",
     "lat": 13.6833, "lng": 79.3475, "festival_dates": ["Brahmotsavam"]},
    {"name": "Rameswaram", "region": "south_india", "state_or_country": "Tamil Nadu, India",
     "deity": "Lord Shiva (Jyotirlinga)", "best_season": "October - April",
     "significance": "Char Dham; bridge between Sri Rama and Lanka.",
     "lat": 9.2876, "lng": 79.3129, "festival_dates": ["Maha Shivaratri"]},
    {"name": "Meenakshi Temple", "region": "south_india", "state_or_country": "Tamil Nadu, India",
     "deity": "Goddess Meenakshi & Lord Sundareswarar", "best_season": "October - March",
     "significance": "Spectacular Dravidian architecture in Madurai.",
     "lat": 9.9195, "lng": 78.1193, "festival_dates": ["Meenakshi Thirukalyanam"]},
    {"name": "Sabarimala", "region": "south_india", "state_or_country": "Kerala, India",
     "deity": "Lord Ayyappa", "elevation_m": 914, "best_season": "November - January",
     "significance": "Forest pilgrimage to Lord Ayyappa.",
     "requires_trek": True, "trek_distance_km": 5.0, "trek_difficulty": "moderate",
     "lat": 9.4364, "lng": 77.0807, "festival_dates": ["Makaravilakku"]},
    {"name": "Murudeshwar", "region": "south_india", "state_or_country": "Karnataka, India",
     "deity": "Lord Shiva", "best_season": "October - March",
     "significance": "Second-tallest Shiva statue overlooking the Arabian Sea.",
     "lat": 14.0937, "lng": 74.4847, "festival_dates": ["Maha Shivaratri"]},
    {"name": "Padmanabhaswamy Temple", "region": "south_india", "state_or_country": "Kerala, India",
     "deity": "Lord Vishnu (Padmanabha)", "best_season": "October - February",
     "significance": "Sacred reclining Vishnu shrine in Thiruvananthapuram.",
     "lat": 8.4827, "lng": 76.9434, "festival_dates": ["Painkuni Utsavam"]},
    {"name": "Kanchipuram", "region": "south_india", "state_or_country": "Tamil Nadu, India",
     "deity": "Multiple shrines", "best_season": "October - March",
     "significance": "City of a thousand temples and a Moksha Puri.",
     "lat": 12.8342, "lng": 79.7036, "festival_dates": ["Brahmotsavam"]},

    # NEPAL
    {"name": "Pashupatinath", "region": "nepal", "state_or_country": "Kathmandu, Nepal",
     "deity": "Lord Shiva", "best_season": "October - March",
     "darshan_timings": "4:00 AM - 9:00 PM",
     "significance": "UNESCO heritage Shiva temple on the Bagmati river.",
     "nearest_airport": "Kathmandu (KTM)", "lat": 27.7106, "lng": 85.3487,
     "festival_dates": ["Maha Shivaratri", "Teej"]},
    {"name": "Muktinath", "region": "nepal", "state_or_country": "Mustang, Nepal",
     "deity": "Lord Vishnu / Avalokiteshvara", "elevation_m": 3710,
     "best_season": "March - June, September - November",
     "significance": "Sacred to Hindus and Buddhists; 108 holy water spouts.",
     "requires_trek": True, "trek_distance_km": 8.0, "trek_difficulty": "moderate",
     "lat": 28.8167, "lng": 83.8714, "festival_dates": ["Yartung Festival"]},
    {"name": "Janakpur", "region": "nepal", "state_or_country": "Janakpur, Nepal",
     "deity": "Goddess Sita", "best_season": "October - March",
     "significance": "Birthplace of Sita and venue of her divine marriage.",
     "lat": 26.7288, "lng": 85.9266, "festival_dates": ["Vivaha Panchami", "Ram Navami"]},
    {"name": "Manakamana", "region": "nepal", "state_or_country": "Gorkha, Nepal",
     "deity": "Goddess Bhagwati", "elevation_m": 1302, "best_season": "October - March",
     "significance": "Wish-fulfilling goddess accessed by cable car.",
     "lat": 27.8989, "lng": 84.6519, "festival_dates": ["Dashain"]},
    {"name": "Lumbini", "region": "nepal", "state_or_country": "Rupandehi, Nepal",
     "deity": "Buddha birthplace", "best_season": "October - March",
     "significance": "Birthplace of Gautama Buddha and UNESCO site.",
     "lat": 27.4833, "lng": 83.2767, "festival_dates": ["Buddha Purnima"]},
    {"name": "Boudhanath", "region": "nepal", "state_or_country": "Kathmandu, Nepal",
     "deity": "Buddhist Stupa", "best_season": "October - March",
     "significance": "Largest stupa in Nepal; UNESCO heritage site.",
     "lat": 27.7215, "lng": 85.3620, "festival_dates": ["Losar"]},
    {"name": "Swayambhunath", "region": "nepal", "state_or_country": "Kathmandu, Nepal",
     "deity": "Buddha / Saraswati", "best_season": "October - March",
     "significance": "The iconic 'Monkey Temple' atop Kathmandu valley.",
     "lat": 27.7148, "lng": 85.2906, "festival_dates": ["Buddha Purnima", "Losar"]},

    # KAILASH
    {"name": "Kailash Mansarovar", "region": "kailash", "state_or_country": "Tibet, China (via Nepal/India)",
     "deity": "Lord Shiva's abode", "elevation_m": 6638, "best_season": "May - September",
     "significance": "Abode of Lord Shiva and most sacred mountain across faiths.",
     "requires_trek": True, "trek_distance_km": 52.0, "trek_difficulty": "hard",
     "vip_darshan": True, "lat": 31.0681, "lng": 81.3119,
     "festival_dates": ["Saga Dawa Festival"]},
    {"name": "Kailash Parikrama", "region": "kailash", "state_or_country": "Tibet, China",
     "deity": "Sacred Kora", "elevation_m": 5648, "best_season": "May - September",
     "significance": "52 km circumambulation around Mt. Kailash.",
     "requires_trek": True, "trek_distance_km": 52.0, "trek_difficulty": "hard",
     "lat": 31.0681, "lng": 81.3119, "festival_dates": ["Saga Dawa Festival"]},
    {"name": "Mansarovar Lake", "region": "kailash", "state_or_country": "Tibet, China",
     "deity": "Holy Lake", "elevation_m": 4590, "best_season": "May - September",
     "significance": "Highest freshwater lake of the world, said to be the lake of Brahma's mind.",
     "lat": 30.6553, "lng": 81.4549, "festival_dates": ["Saga Dawa Festival"]},
]


# Map images to temples by deity/region
TEMPLE_IMAGES = [
    "https://images.unsplash.com/photo-1677434654722-69e7ba88b4ef?w=900",
    "https://images.unsplash.com/photo-1554554497-0095c34db3ec?w=900",
    "https://images.unsplash.com/photo-1599831069477-b2acdc0bcb91?w=900",
    "https://images.unsplash.com/photo-1645033393602-4f7623917853?w=900",
    "https://images.unsplash.com/photo-1637846959991-18e54d6e2035?w=900",
]


def build_temples():
    out = []
    for i, t in enumerate(TEMPLES_RAW):
        t = dict(t)
        t["id"] = slugify(t["name"])
        t["slug"] = slugify(t["name"])
        t.setdefault("image_url", TEMPLE_IMAGES[i % len(TEMPLE_IMAGES)])
        t.setdefault("avg_rating", round(4.4 + (i % 6) * 0.1, 1))
        out.append(t)
    return out


PACKAGES_RAW = [
    {
        "title": "Char Dham Yatra — Classic 11 Days",
        "slug": "char-dham-classic-11-days",
        "summary": "The complete Yamunotri, Gangotri, Kedarnath and Badrinath circuit by road with comfort hotels and experienced priests.",
        "duration_days": 11,
        "base_price_inr": 48500.0,
        "luxury_price_inr": 89500.0,
        "region": "north_india",
        "transport_modes": ["bus", "train"],
        "temples_included": ["yamunotri", "gangotri", "kedarnath", "badrinath"],
        "inclusions": ["3-star/Deluxe hotels with breakfast & dinner",
                        "AC SUV transport",
                        "Local priests for puja & rituals",
                        "VIP darshan assistance",
                        "Medical kit & oxygen support"],
        "exclusions": ["Helicopter for Kedarnath (optional add-on)", "Personal expenses", "Trip insurance"],
        "hero_image": "https://images.unsplash.com/photo-1637846959991-18e54d6e2035?w=1400",
        "highlights": ["Ganga Aarti at Haridwar", "Helipad upgrade available",
                       "Doctor on call", "Senior-citizen friendly itinerary"],
        "difficulty": "moderate",
        "category": "pilgrimage",
    },
    {
        "title": "Kailash Mansarovar — Helicopter Express",
        "slug": "kailash-mansarovar-helicopter-express",
        "summary": "Premium 11-day Kailash Mansarovar Yatra via Kathmandu with helicopter from Simikot to Hilsa.",
        "duration_days": 11,
        "base_price_inr": 248000.0,
        "luxury_price_inr": 395000.0,
        "region": "kailash",
        "transport_modes": ["flight", "helicopter"],
        "temples_included": ["kailash-mansarovar", "kailash-parikrama", "mansarovar-lake", "pashupatinath"],
        "inclusions": ["International & domestic flights",
                        "Helicopter Simikot ↔ Hilsa",
                        "Tibet permits & visa support",
                        "Acclimatisation hotels in Kathmandu & Saga",
                        "Yak/porter support for Parikrama",
                        "Oxygen, doctor and medical evacuation insurance"],
        "exclusions": ["Personal trekking gear", "Tips for support staff", "Optional helicopter Yam Dwar transfer"],
        "hero_image": "https://images.unsplash.com/photo-1645033393602-4f7623917853?w=1400",
        "highlights": ["Sacred kora around Mt Kailash", "Holy bath at Mansarovar",
                       "Sunrise darshan from Tarboche", "Doctor + oxygen onboard"],
        "difficulty": "hard",
        "category": "helicopter",
    },
    {
        "title": "Do Dham — Kedarnath & Badrinath Heli Combo",
        "slug": "do-dham-kedarnath-badrinath-heli",
        "summary": "5-day twin Dham experience with helicopter for Kedarnath and luxury road for Badrinath.",
        "duration_days": 5,
        "base_price_inr": 68500.0,
        "luxury_price_inr": 124000.0,
        "region": "north_india",
        "transport_modes": ["helicopter", "flight"],
        "temples_included": ["kedarnath", "badrinath"],
        "inclusions": ["Helicopter Phata ↔ Kedarnath",
                        "Premium hotels", "VIP darshan", "Airport transfers"],
        "exclusions": ["Personal shopping", "Travel insurance"],
        "hero_image": "https://images.unsplash.com/photo-1637846959991-18e54d6e2035?w=1400",
        "highlights": ["Skip-the-queue VIP darshan", "Senior-friendly heli option",
                       "Pickup from Dehradun airport"],
        "difficulty": "easy",
        "category": "helicopter",
    },
    {
        "title": "South India Temple Circuit — 9 Days",
        "slug": "south-india-temple-circuit-9-days",
        "summary": "Tirupati, Rameswaram, Madurai Meenakshi, Kanchipuram and Padmanabhaswamy in a single divine sweep.",
        "duration_days": 9,
        "base_price_inr": 42500.0,
        "luxury_price_inr": 78000.0,
        "region": "south_india",
        "transport_modes": ["flight", "train"],
        "temples_included": ["tirupati-balaji", "rameswaram", "meenakshi-temple",
                              "kanchipuram", "padmanabhaswamy-temple"],
        "inclusions": ["AC train and flight tickets",
                        "Heritage stays", "Local sadhguru-curated rituals", "All meals"],
        "exclusions": ["Special darshan donations", "Camera fees"],
        "hero_image": "https://images.unsplash.com/photo-1554554497-0095c34db3ec?w=1400",
        "highlights": ["VIP Suprabhatam at Tirupati", "Heritage walks in Madurai",
                       "Backwater cruise add-on in Kerala"],
        "difficulty": "easy",
        "category": "pilgrimage",
    },
    {
        "title": "Nepal Spiritual Trail — Pashupatinath, Muktinath & Lumbini",
        "slug": "nepal-spiritual-trail",
        "summary": "Pashupatinath darshan, holy bath at Muktinath and walk in Lumbini, the Buddha's birthplace.",
        "duration_days": 7,
        "base_price_inr": 58000.0,
        "luxury_price_inr": 96000.0,
        "region": "nepal",
        "transport_modes": ["flight"],
        "temples_included": ["pashupatinath", "muktinath", "lumbini", "boudhanath", "swayambhunath"],
        "inclusions": ["International flights", "5-star Kathmandu stay",
                        "Pokhara to Jomsom flight", "Local guide & priest"],
        "exclusions": ["Nepal visa fee", "Personal expenses"],
        "hero_image": "https://images.unsplash.com/photo-1645033393602-4f7623917853?w=1400",
        "highlights": ["108 sacred water spouts at Muktinath",
                       "Heritage walk in Kathmandu Durbar Square",
                       "Sunrise from Sarangkot"],
        "difficulty": "moderate",
        "category": "pilgrimage",
    },
    {
        "title": "Jyotirlinga Yatra — 12 Sacred Shivlingas",
        "slug": "jyotirlinga-yatra-12-sacred",
        "summary": "All twelve Jyotirlingas across India in a meticulously planned 18-day yatra.",
        "duration_days": 18,
        "base_price_inr": 124000.0,
        "luxury_price_inr": 215000.0,
        "region": "central_india",
        "transport_modes": ["flight", "train", "bus"],
        "temples_included": ["somnath", "kashi-vishwanath", "kedarnath", "ujjain-mahakaleshwar",
                              "omkareshwar", "trimbakeshwar", "baidyanath-dham", "rameswaram"],
        "inclusions": ["End-to-end transport", "Hotels with breakfast & dinner",
                        "Priest & ritual fee", "VIP darshan where available"],
        "exclusions": ["Optional helicopter for Kedarnath", "Travel insurance"],
        "hero_image": "https://images.unsplash.com/photo-1554554497-0095c34db3ec?w=1400",
        "highlights": ["Bhasma Aarti at Ujjain", "Submerged darshan at Somnath",
                       "Ganga Aarti at Kashi"],
        "difficulty": "moderate",
        "category": "pilgrimage",
    },
    {
        "title": "Amarnath Yatra — 6 Days Helicopter",
        "slug": "amarnath-yatra-6-days-helicopter",
        "summary": "Comfortable Amarnath darshan with helicopter from Baltal and stay in Srinagar.",
        "duration_days": 6,
        "base_price_inr": 52000.0,
        "luxury_price_inr": 89000.0,
        "region": "north_india",
        "transport_modes": ["helicopter", "flight"],
        "temples_included": ["amarnath"],
        "inclusions": ["Helicopter Neelgrath ↔ Panjtarni",
                        "Houseboat stay in Srinagar",
                        "Yatri permit assistance",
                        "Pony assistance to cave"],
        "exclusions": ["Personal medical kit",
                        "Optional sightseeing in Srinagar"],
        "hero_image": "https://images.unsplash.com/photo-1645033393602-4f7623917853?w=1400",
        "highlights": ["Ice lingam darshan", "Helicopter scenic flight", "Shikara ride in Dal Lake"],
        "difficulty": "moderate",
        "category": "helicopter",
    },
    {
        "title": "Vaishno Devi Express — Weekend Heli",
        "slug": "vaishno-devi-weekend-heli",
        "summary": "Weekend escape from Delhi/Mumbai with helicopter from Katra to Sanjichhat.",
        "duration_days": 3,
        "base_price_inr": 24500.0,
        "luxury_price_inr": 42000.0,
        "region": "north_india",
        "transport_modes": ["flight", "helicopter"],
        "temples_included": ["vaishno-devi"],
        "inclusions": ["Return flight", "Helicopter Katra ↔ Sanjichhat",
                        "Hotel in Katra", "VIP darshan ticket"],
        "exclusions": ["Personal expenses", "Pony / palki charges"],
        "hero_image": "https://images.unsplash.com/photo-1637846959991-18e54d6e2035?w=1400",
        "highlights": ["Skip-the-queue VIP entry",
                       "Bhairavnath darshan included",
                       "Senior citizen friendly"],
        "difficulty": "easy",
        "category": "helicopter",
    },
]


def build_packages():
    return [dict(p) for p in PACKAGES_RAW]
